version: 0.2
phases:

  pre_build:
    commands:
        - echo Conectando con el Registro de Contenedores...
        - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 972067303079.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Construyendo la imagen Docker...
      - docker build -t pegasus/repository .
      - echo Etiquetando la imagen Docker...
      - docker tag pegasus/repository:latest 972067303079.dkr.ecr.us-east-1.amazonaws.com/pegasus/repository:latest

    post_build:
      commands:
        - echo Enviando la imagen Docker al Registro...
        - docker push 972067303079.dkr.ecr.us-east-1.amazonaws.com/pegasus/repository:latest
        - echo Construcción y push completados.


artifacts:
    files:
        - '**/*'