version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - echo Instalando Dependencias...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Corriendo Pruebas...
      - python -m pytest --junitxml=reports/test-results.xml -v
      - echo Pruebas Completadas fix 6
reports:
  pytest_reports:
    files:
      - test-results.xml
    base-directory: reports
    file-format: JUNITXML

artifacts:
    files:
        - '**/*'