version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - echo Instalando Dependencias...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Corriendo Pruebas...
      - python -m pytest --junitxml=reports/test-results.xml -v
      - echo Pruebas Completadas.
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Empaquetando Proyecto
      - mkdir -p dist
      - zip -r dist/entrega2_pegasus_artifact.zip application.py endpoints.py models.py requirements.txt
      - echo Empaquetado Completo.

artifacts:
  files:
    - entrega2_pegasus_artifact.zip
  base-directory: dist
  discard-paths: yes

reports:
  pytest_reports:
    files:
      - test-results.xml
    base-directory: reports
    file-format: JUNITXML