### GET request to example server
GET http://localhost:5000/blacklists/test@example.com
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc2MDAyMDgzMiwianRpIjoiNTE2ZTc5MGEtOWVkOS00NDUwLWJiNTctMTkxMTYxNjhkYTRkIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkRlZmF1bHRVc2VyIiwibmJmIjoxNzYwMDIwODMyLCJjc3JmIjoiOWNhNThmMTMtOTBiZi00Y2NjLWI3MmUtZWI1ZmQwMzY4OGU5IiwiZXhwIjoxNzY1MjA0ODMyfQ.NgwyLsqFhzRXV5cpuN5yVdINlTZNocwuo-CD47HU_W8
###


POST http://localhost:5000/blacklists
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc2MDAyMDgzMiwianRpIjoiNTE2ZTc5MGEtOWVkOS00NDUwLWJiNTctMTkxMTYxNjhkYTRkIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkRlZmF1bHRVc2VyIiwibmJmIjoxNzYwMDIwODMyLCJjc3JmIjoiOWNhNThmMTMtOTBiZi00Y2NjLWI3MmUtZWI1ZmQwMzY4OGU5IiwiZXhwIjoxNzY1MjA0ODMyfQ.NgwyLsqFhzRXV5cpuN5yVdINlTZNocwuo-CD47HU_W8
Content-Type: application/json

{
    "email": "test@example.com",
    "app_uuid": "{{$uuid}}",
    "blocked_reason": "Example Reason"
}